# -*- mode: ruby -*-
# vi: set ft=ruby :

# linux VM for forensic analysis

Vagrant.configure("2") do |config|

  config.vm.define "soc" do |lab|
    lab.vm.box = UBUNTU
    lab.vm.hostname = "soc"
    lab.vm.network "public_network"
    lab.vm.disk :disk, size:"40GB", primary: true

    lab.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "soc"
    end

    lab.vm.provision "shell", path: "./scripts/install.sh"
    lab.vm.provision "shell", path: "./scripts/file_sharing.sh"
    lab.vm.provision "shell", path: "./scripts/file_analysis.sh"
    lab.vm.provision "shell", path: "./scripts/volatility.sh"
    lab.vm.provision "shell", path: "./scripts/velociraptor.sh"
    lab.vm.provision "shell", path: "./scripts/cyberchef.sh"
  end
end
