# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.2"



Vagrant.configure("2") do |config|

  config.vm.define "forensic" do |lab|
    lab.vm.box = UBUNTU
    lab.vm.hostname = "flare"
    lab.vm.network "public_network"
    lab.vm.disk :disk, size:"40GB", primary: true
    lab.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "forensic"
    end
  end
end

Vagrant.configure("2") do |config|
    config.vm.define "vagrant-windows_10_analyst_virtualbox"
    config.vm.box = "windows_10_analyst"
    config.vm.communicator = "winrm"

    # Admin user name and password
    config.winrm.username = "analyst"
    config.winrm.password = "analyst"

    config.vm.guest = :windows
    config.windows.halt_timeout = 15

    config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true

    config.vm.provider :virtualbox do |v, override|
        #v.gui = true
        v.customize ["modifyvm", :id, "--memory", 2048]
        v.customize ["modifyvm", :id, "--cpus", 2]
        v.customize ["modifyvm", :id, "--vram", 128]
        v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        v.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
        v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end

    config.vm.provision "shell", inline: <<-SHELL
        choco install 7zip.install --pre -y
        choco install git.install -y
        #choco install libreoffice-fresh -y
        choco install vscode -y
        choco install sysinternals -y
        choco install googlechrome -y
        choco install wireshark -y
        choco install microsoft-windows-terminal -y
    SHELL

    config.vm.provision "shell", path: "../scripts/memprocfs.ps1", privileged: true
    config.vm.provision "shell", path: "../scripts/zircolite.ps1", privileged: false
    config.vm.provision "shell", path: "../scripts/ftk-imager.ps1"

end
